### ISSUE TITLE
KHÔNG QUAY LẠI RETURN URL

### ISSUE THREAD

**Issue by Onnv7** [justaboy-dev/VNPay_Flutter#2]
Em chào anh, em có dùng vnpay bên flutter từ thư viện của anh trên pubdev. Nhưng khi thanh toán thành công thì nó close luôn web mà không đến trang returnUrl, em không biết đó có phải lỗi hay là do nghiệp vụ trên mobile là không cần đi đến trang returnUrl ạ?
![image](https://github.com/justaboy-dev/VNPay_Flutter/assets/75663685/4f5f9f97-58cd-4d57-bb56-bbdc4473ca64)

**Comment by justaboy-dev** [comment]
Hi chào bạn. Sorry bạn vì mình khá bận nên không check mail.
Flow thanh toán VNPAY trên mobile mình không cần đi đến returnUrl mà chỉ
cần handle 2 case success hoặc failure (dựa vào response code từ phía
VNPAY) thôi nhé. returnUrl chỉ nên dùng nếu bạn làm web (Sau khi thanh toán
xong thì redirect sang đâu thôi)

Vào Th 7, 30 thg 9, 2023 lúc 21:10 Nguyễn Văn An ***@***.***>
đã viết:

**Comment by Onnv7** [comment]
Dạ em cảm ơn anh ạ ^^
