### ISSUE TITLE
Cứu em mấy anh ơi

### ISSUE THREAD

**Issue by tiendev2003** [justaboy-dev/VNPay_Flutter#8]
Because date_app_team depends on vnpay_flutter ^1.0.2 which depends on intl ^0.17.0, intl ^0.17.0 is required.
Tức là em có 1 thư viện cần  intl ^0.19.0 mà h tải thêm vnpay_flutter  thì lại yêu cầu  intl ^0.17.0. căng quá ạ

**Comment by justaboy-dev** [comment]
Hi, bạn có thể sử dụng phiên bản 1.0.3 nhé. Lưu ý: Để dùng được intl 0.19.0, bạn phải dùng Dart SDK trên 3.0 nhé

Best regards
